export const NotificationEvent = {
    RESERVATION_CREATED: "RESERVATION_CREATED",
    RESERVATION_READY: "RESERVATION_READY",
    RESERVATION_EXPIRING_SOON: "RESERVATION_EXPIRING_SOON",
    RESERVATION_EXPIRED: "RESERVATION_EXPIRED",
    LOAN_CREATED: "LOAN_CREATED",
    LOAN_DUE_SOON: "LOAN_DUE_SOON",
    LOAN_OVERDUE: "LOAN_OVERDUE",
    USER_SUSPENDED: "USER_SUSPENDED",
};